export const GET_CITY_DATA = 'GET_CITY_DATA';
export const GET_CITY_DATA_SUCCESS = 'GET_CITY_DATA_SUCCESS';
export const GET_CITY_WEATHER_DATA = 'GET_CITY_WEATHER_DATA';
export const GET_CITY_WEATHER_DATA_SUCCESS = 'GET_CITY_WEATHER_DATA_SUCCESS';

export const GET_FAVORITES_LIST = 'GET_FAVORITES_LIST';
export const GET_FAVORITES_LIST_SUCCESS = 'GET_FAVORITES_LIST_SUCCESS';
export const ADD_ITEM_TO_FAVORITES = 'ADD_ITEM_TO_FAVORITES';
export const ADD_ITEM_TO_FAVORITES_SUCCESS = 'ADD_ITEM_TO_FAVORITES_SUCCESS';
export const REMOVE_ITEM_FROM_FAVORITES = 'REMOVE_ITEM_FROM_FAVORITES';
export const REMOVE_ITEM_FROM_FAVORITES_SUCCESS = 'REMOVE_ITEM_FROM_FAVORITES_SUCCESS';

export const GET_SEARCH_DATA = 'GET_SEARCH_DATA';
export const GET_SEARCH_DATA_SUCCESS = 'GET_SEARCH_DATA_SUCCESS';
